# Generated by Django 5.1.7 on 2025-03-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_jobapplication_status_jobinterview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinterview',
            name='meeting_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
