# Generated by Django 5.1.7 on 2025-03-24 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_jobinterview_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinterview',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conducted_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobinterview',
            name='interviewer_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobinterview',
            name='interviewer_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('candidate', 'Candidate'), ('department_manager', 'Department Manager'), ('hr_coordinator', 'HR Coordinator'), ('interviewer', 'Interviewer')], default='candidate', max_length=20),
        ),
    ]
